# Generated by Django 6.0.1 on 2026-01-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VGForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNum', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completionStatus', models.CharField(choices=[('ND', 'No Dungeon'), ('FD', 'First Dungeon'), ('SD', 'Second Dungeon'), ('TD', 'Third Dungeon')], default='ND', max_length=4)),
                ('additionalcomments', models.TextField()),
            ],
        ),
    ]
