# Generated by Django 6.0.1 on 2026-02-04 02:59

import datetime
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGForum', '0003_alter_vgform_created_alter_vgform_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgform',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 2, 4, 2, 59, 32, 547057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vgform',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
