# Generated by Django 6.0.1 on 2026-02-04 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGForum', '0004_alter_vgform_created_alter_vgform_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgform',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
